on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - tworkflow-0926-2-test

jobs:
  get-changed-project-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Git Diff
        uses: technote-space/get-diff-action@v6
      - name: Get Changed Project and Stack
        id: get-changed-project-and-stack
        run: |
          curl https://kusionstack.io/scripts/install.sh | sh
          export CHANGED_PATHS="${{ steps.git-diff.outputs.diff }}"
          python3 hack/get_changed_project_stack.py
          echo "Changed projects: ${{ steps.get-changed-project-and-stack.outputs.changed_projects }}"
          echo "Changed stacks: ${{ steps.get-changed-project-and-stack.outputs.changed_stacks }}"
    outputs:
      changed_projects: ${{ steps.get-changed-project-and-stack.outputs.changed_projects }}
      changed_stacks: ${{ steps.get-changed-project-and-stack.outputs.changed_stacks }}

  check-structure:
    needs: get-changed-project-stack
    runs-on: ubuntu-latest
    container:
      image: kusionstack/kusion:latest
      env:
        CHANGED_PROJECTS: ${{ needs.get-changed-project-stack.outputs.changed_projects }}
        CHANGED_STACKS: ${{ needs.get-changed-project-stack.outputs.changed_stacks }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Pytest Html
        run: python3 -m pip install pytest-html pyyaml -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
      - name: Check Structure
        run: python3 -m pytest -v hack/check_structure.py --junitxml ./hack/report/check-structure.xml --html ./hack/report/check-structure.html
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: check-structure-report
          path: |
            hack/report/check-structure.xml
            hack/report/check-structure.html

  test-correctness:
    needs: get-changed-project-stack
    runs-on: ubuntu-latest
    container:
      image: kusionstack/kusion:latest
      env:
        CHANGED_STACKS: ${{ needs.get-changed-project-stack.outputs.changed_stacks }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Pytest Html
        run: python3 -m pip install pytest-html pyyaml -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
      - name: Test Correctness
        run: python3 -m pytest -v hack/test_correctness.py --junitxml ./hack/report/test-correctness.xml --html ./hack/report/test-correctness.html
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-correctness-report
          path: |
            hack/report/test-correctness.xml
            hack/report/test-correctness.html        

  preview:
    needs: [ check-structure, test-correctness ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Kusion
        run: curl https://kusionstack.io/scripts/install.sh | bash
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup K3d&K3s
        uses: nolar/setup-k3d-k3s@v1
      - name: Preview
        id: preview
        run: |
          export CHANGED_STACKS="${{ needs.get-changed-project-stack.outputs.changed_stacks }}"
          python3 hack/preview_changed_stacks.py
      - name: Upload Report
        if: ${{ steps.preview.outputs.preview_success }}
        uses: actions/upload-artifact@v2
        with:
          name: preview-report
          path: hack/report/preview-result.zip

  apply:
    needs: preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Kusion
        run: sudo curl https://kusionstack.io/scripts/install.sh | sh
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup K3d&K3s
        uses: nolar/setup-k3d-k3s@v1
      - name: Apply
        id: apply
        run: |
          export CHANGED_STACKS="${{ needs.get-changed-project-stack.outputs.changed_stacks }}"
          python3 hack/apply_changed_stacks.py
      - name: Upload Report
        if: ${{ steps.apply.outputs.apply_success }}
        uses: actions/upload-artifact@v2
        with:
          name: apply-report
          path: hack/report/apply-result.zip

  # deprecated checkpoints. need upgrade
  # lint:
  #   needs: deps
  #   runs-on: ubuntu-latest
  #   container:
  #     image: kusionstack/kusion:latest
  #     env:
  #       CHANGED_FILE: ${{needs.diff.outputs.CHANGED_FILE}}
  #       AFFECTED_STACKS: ${{needs.deps.outputs.affected_stacks}}
  #       AFFECTED_PROJECTS: ${{needs.deps.outputs.affected_projs}}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - id: install-pytest-html
  #       run: |
  #         python3 -m pip install pytest-html pytest-xdist ruamel.yaml -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
  #         # todo: the following script is to workaround "missing kclvm_cli" error, after the problem solved in the kclvm v0.4.6, this can be removed
  #         apt -y install wget
  #         wget -c https://github.com/KusionStack/KCLVM/releases/download/v0.4.6.2/kclvm-v0.4.6.2-linux-amd64.tar.gz -qO - | tar xz -C ./
  #     - id: lint-check
  #       run: |
  #         export PATH=$PATH:$(pwd)/kclvm/bin
  #         python3 -m pytest -v -n 5 hack/lint_check.py --junitxml ./hack/report/lint.xml --html=./hack/report/lint.html
  #     - id: upload-lint-report
  #       if: always()
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: lint-report
  #         path: |
  #           hack/report/lint.xml
  #           hack/report/lint.html
